BlogApp/Models/ErrorViewModel.cs
namespace BlogApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogApp/Models/LoginAttempt.cs
namespace BlogApp.Models
{
    public class LoginAttempt
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public int FailedAttempts { get; set; }
        public DateTime LastFailedAttempt { get; set; }
    }
}

BlogApp/Models/LoginDto.cs
using System.ComponentModel.DataAnnotations;

namespace BlogApp.Models
{
    public class LoginDto
    {
        
        public string Email { get; set; }

        public string Password { get; set; }
    }
}

BlogApp/Models/RegisterDto.cs
using System.ComponentModel.DataAnnotations;

namespace BlogApp.Models
{
    public class RegisterDto
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "First Name is required.")]
        [Display(Name = "FirstName")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is required.")]
        [Display(Name = "LastName")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Username is required.")]
        [Display(Name = "UserName")]
        public string UserName { get; set; }


        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [StringLength(100, MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

BlogApp/Controllers/AuthenticationController.cs
using BlogApp.Models;
using BlogApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly ApplicationDbContext context;
        private const int MaxFailedAttempts = 3; // Max failed login attempts before lockout
        private const int LockoutDurationInMinutes = 5; // Lockout duration in minutes


        public AuthenticationController(ApplicationDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult Login() 
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(RegisterDto model)
        {
            if(ModelState.IsValid)
            {
                var registerdto = new RegisterDto()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    UserName = model.UserName,
                    Email = model.Email,
                    Password = model.Password,

                };

                context.Register.Add(registerdto);
                context.SaveChanges();

                return RedirectToAction("Index","Authentication");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Login(LoginDto login)
        {
           
                var user = context.Register.SingleOrDefault(u => u.Email == login.Email);

                if (user == null)
                {
                    ModelState.AddModelError("Email", "Email is not registered");
                    return View(login);
                }

                var loginAttempt = context.LoginAttempts.FirstOrDefault(la => la.Username == login.Email);

                if (loginAttempt == null)
                {
                    loginAttempt = new LoginAttempt()
                    {
                        Username = login.Email,
                        FailedAttempts = 0,
                        LastFailedAttempt = DateTime.Now
                    };

                    context.LoginAttempts.Add(loginAttempt);
                    context.SaveChanges();
                }


                if (loginAttempt.FailedAttempts >= MaxFailedAttempts)
                {
                    if ((DateTime.Now - loginAttempt.LastFailedAttempt).TotalMinutes < LockoutDurationInMinutes)
                    {
                        ViewBag.Error = "Your account is locked. Please try again after 5 minutes.";
                        return View();
                    }
                    else
                    {
                        // reset failed attempts if the login time hass passed out
                        loginAttempt.FailedAttempts = 0;
                        context.LoginAttempts.Update(loginAttempt);
                        context.SaveChanges();
                    }
                }

                if (user.Password == login.Password)
                {
                    loginAttempt.FailedAttempts = 0;
                    context.LoginAttempts.Update(loginAttempt);
                    context.SaveChanges();

					return RedirectToAction("Index", "Dashboard", new { id = user.Id });
				}
                else
                {
                    ModelState.AddModelError("Password", "Incorrect password.");
                    


					loginAttempt.FailedAttempts++;
					loginAttempt.LastFailedAttempt = DateTime.Now;
					context.LoginAttempts.Update(loginAttempt);
					context.SaveChanges();

					return View(login);
				}
		}
    }
}

BlogApp/Controllers/DashboardController.cs
using BlogApp.Models;
using BlogApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;

namespace BlogApp.Controllers
{
	public class DashboardController : Controller
	{
		private readonly ApplicationDbContext context;

		public DashboardController(ApplicationDbContext context) 
		{
			this.context = context;
		}

		public IActionResult Index(int id)
		{
			ViewData["Id"] = id;
			return View();
		}

		public IActionResult Profile(int id)
		{
			// getting all the data of the user from register table
			var user = context.Register.FirstOrDefault(x => x.Id == id);

			if(user == null)
			{
				return NotFound();
			}

			ViewData["Id"] = user.Id;
			ViewData["UserName"] = user.UserName;
			ViewData["FirstName"] = user.FirstName;
			ViewData["LastName"] = user.LastName;
			ViewData["Email"] = user.Email;
			ViewData["Password"] = user.Password;


			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Updatingprofile(RegisterDto model)
		{
			var user = context.Register.FirstOrDefault(p=>p.Id == model.Id);

			if(user == null)
			{
				return NotFound();
			}

			user.FirstName = model.FirstName;
			user.LastName = model.LastName;
			user.UserName = model.UserName;
			user.Email = model.Email;
			user.Password = model.Password;

			context.SaveChanges();

			return RedirectToAction("Index", "Dashboard", new { id = user.Id });
		}

		public IActionResult Logout()
		{
			return RedirectToAction("Index","Authentication");
		}
	}
}

BlogApp/Controllers/FrontEndController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.Controllers
{
    public class FrontEndController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }
    }
}

BlogApp/Controllers/HomeController.cs
using BlogApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogApp/Views/Authentication/Index.cshtml
<a class="btn btn-primary" asp-controller="Authentication" asp-action="Register"> Register</a>
<a class="btn btn-primary" asp-controller="Authentication" asp-action="Login">Login</a>

BlogApp/Views/Authentication/Login.cshtml
@model LoginDto
	
<div class="container">
	<div class="row">

		<form method="post" asp-controller="Authentication" asp-action="Login">
			<div class="col-md-6">
				<label>Email</label>
				<input class="form-control" type="text" asp-for="Email" />
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>

			<div class="col-md-6">
				<label>Password</label>
				<input class="form-control" type="password" asp-for="Password" />
				<span asp-validation-for="Password" class="text-danger"></span>
			</div>

			<div class="col-md-6">
				<button type="submit" class="btn btn-primary">Login</button>
			</div>

			
		</form>
		
		@if (ViewBag.Error != null)
		{
			<div class="alert alert-danger">
				@ViewBag.Error
			</div>
		}
	</div>
</div>

BlogApp/Views/Authentication/Register.cshtml
@model RegisterDto

<div class="container">
	<div class="row">

		<form method="post" asp-controller="Authentication" asp-action="Register">


			<div class="col-md-6">
				<label>First Name</label>
				<input class="form-control" type="text" asp-for="FirstName" />
				<span asp-validation-for="FirstName" class="text-danger"></span>
			</div>

			<div class="col-md-6">
				<label>Last Name</label>
				<input class="form-control" type="text" asp-for="LastName" />
				<span asp-validation-for="LastName" class="text-danger"></span>
			</div>

			<div class="col-md-6">
				<label>User Name</label>
				<input class="form-control" type="text" asp-for="UserName" />
				<span asp-validation-for="UserName" class="text-danger"></span>
			</div>

			<div class="col-md-6">
				<label>Email</label>
				<input class="form-control" type="text" asp-for="Email" />
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>

			<div class="col-md-6">
				<label>Password</label>
				<input class="form-control" type="password" asp-for="Password" />
				<span asp-validation-for="Password" class="text-danger"></span>
			</div>

			<div class="col-md-6">
				<button type="submit" class="btn btn-primary">Register</button>
			</div>
		</form>
		
	</div>
</div>

BlogApp/Views/Dashboard/Index.cshtml
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<a class="btn btn-primary" asp-controller="Dashboard" asp-action="Profile" asp-route-id="@ViewData["Id"]">Profile</a>
			
		</div>

		<div class="col-md-2">
			<a class="btn btn-primary" asp-controller="Dashboard" asp-action="Logout">Logout</a>
		</div>
		
	</div>
</div>

BlogApp/Views/Dashboard/Profile.cshtml
@model RegisterDto


<div class="container">
	<div class="row">

		<form method="post" asp-controller="Dashboard" asp-action="Updatingprofile">
			<div class="col-md-6">
				<label>Id</label>
				<input type="text" class="form-control" value="@ViewData["Id"]" asp-for="Id" readonly/>
			</div>

			<div class="col-md-6">
				<label>First Name</label>
				<input type="text" class="form-control" value="@ViewData["FirstName"]" asp-for="FirstName" />
			</div>

			<div class="col-md-6">
				<label>Last Name</label>
				<input type="text" class="form-control" value="@ViewData["LastName"]" asp-for="LastName" />
			</div>

			<div class="col-md-6">
				<label>UserName</label>
				<input type="text" class="form-control" value="@ViewData["UserName"]" asp-for="UserName" />
			</div>

			<div class="col-md-6">
				<label>Email</label>
				<input type="text" class="form-control" value="@ViewData["Email"]" asp-for="Email"/>
			</div>

			<div class="col-md-6">
				<label>Password</label>
				<input type="password" class="form-control" value="@ViewData["Password"]" asp-for="Password" />
			</div>

			<div class="col-md-6">
				<button type="submit" class="btn btn-primary">Update</button>
			</div>
		</form>
		
	</div>
</div>

BlogApp/Views/FrontEnd/Index.cshtml
<header class="navbarheader">
	<div class="container mynavbar">
		<div class="row navbarrow">
			<div class="col-md-3 col-sm-12 navbarlink">
				<a href="#">Blog Website</a>
			</div>

			<div class="col-md-9 col-sm-12 text-end navbarlinks">
				<a href="#">HOME</a>
				<a href="#">ABOUT</a>
				<a href="#">SERVICE</a>
				<a href="#">CONTACT US</a>
			</div>
		</div>
	</div>

	<div class="container navbarmaincontent">
		<div class="row">
			<div class="col-md-6 col-sm-12">
				<p class="navbarparagraph">Welcome to Our Blog Website</p>
			</div>

			<div class="col-md-6 col-sm-12">
				<button type="submit">Contact Us</button>
			</div>
			
		</div>
	</div>
</header>

<section>
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-12 main-content1">
				<h2>About Us</h2>
				<p class="navbarparagraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
			<div class="col-md-6 col-sm-12 main-content2" >
				<p class="navbarparagraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
		</div>
	</div>
</section>

<section class="model-popup">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<h1>At your Service</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 col-sm-12">
				<img src="~/images/s-1.png" width="50px" height="50px"/>
				<h2>Written with your love</h2>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content t, </p>
				<button>Read More</button>
				<br />
				<br />
				<br />
				<img src="~/images/s-3.png" width="50px" height="50px" />
				<h2>Up-to-date</h2>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content t, </p>
				<button>Read More</button>
			</div>

			<div class="col-md-6 col-sm-12">
				<img src="~/images/s-2.png" width="50px" height="50px" />
				<h2>Fast Turnaround</h2>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content t, </p>
				<button>Read More</button>
				<br />
				<br />
				<br />
				<img src="~/images/s-4.png" width="50px" height="50px" />
				<h2>Premium Content</h2>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content t, </p>
				<button>Read More</button>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8 col-sm-12">
				<h2>Get Your Quote</h2>
				<p>It is a long established fact that a reader will be distracted by the readable content of a page</p>
			</div>

			<div class="col-md-4 col-sm-12">
				<button>Get Your Quote</button>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12 col-sm-12 text-center mt-5">
				<h1 class="touchheading">Let's Get In Touch! </h1>
			</div>
		</div>

		<div class="row contactusformandimage pt-5 pb-4">
			<div class="col-md-6 col-sm-12">
				@* @using (Html.BeginForm("Contact", "FrontEnd", FormMethod.Post))
				{
						@Html.Label("Name");
						@Html.TextBox("Name");
						<br />
						@Html.Label("Email");
						@Html.TextBox("Email");
						<br />
						@Html.Label("Message");
						@Html.TextArea("Message", "Message", new { @class = "form-control", rows = 5, cols = 20 });
						<br />
						<button type="submit">Send</button>
				} *@

				<form method="post" asp-controller="FrontEnd" asp-action="Contact">
					<input type="text" placeholder="Name" class="form-control"/>
					<br />
					<input type="text" placeholder="Email" class="form-control" />
					<br />
					<textarea rows="5" cols="20" placeholder="Message" class="form-control"></textarea>
					<br />
					<button type="submit">Send</button>
				</form>
				
			</div>
			<div class="col-md-6 col-sm-12">
				<img src="~/images/contact-img.jpg"/>
			</div>
		</div>
	</div>

</section>

<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h2 class="touchheading text-center">Contact Us</h2>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<i class="fa fa-location-dot"></i>
				<i class="fa fa-phone"></i>
				<i class="fa fa-message"></i>
				
			</div>
		</div>
	</div>
</section>

BlogApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlogApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogApp.styles.css" asp-append-version="true" />


    <link rel="stylesheet" href="~/css/frontendIndex.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
   @*  <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FrontEnd" asp-action="Index">Blog Website</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@
    
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BlogApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/js/frontendIndex.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>